package tsukimi:extension;

world extension {
    import utils: interface {
        read-file: func(path: string) -> option<string>;
    }
    export iadd: interface {
            // variant content {
            //     text(string),
            //     title(string)
            // }
            // resource iterator {
            //     next: func() -> option<string>;
            // }
            // add: func(x: u32, y: u32) -> u32;
            // init: func(iterator) -> iterator;



            add-to-gitignore: func() -> string;

            variant decoder-entry {
                next-file(string),
                text-entry(tuple<string, u64, u64>)
            }

            decode: func() -> stream<decoder-entry>;

            // is-engine: func() -> stream<bool>;
        }
}
