services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tsukimi
      POSTGRES_PASSWORD: tsukimi
      POSTGRES_DB: tsukimi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  web:
    build:
      context: ./tsukimi-web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./tsukimi-web:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./tsukimi-web/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./tsukimi-web:/app
  #     - ./tsukimi-core:/tsukimi-core
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - postgres
  #     - api
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  api:
    build:
      context: .
      dockerfile: ./tsukimi-api/Dockerfile
    volumes:
      - ./tsukimi-api/src:/app/src
      - ./tsukimi-api/Cargo.toml:/app/Cargo.toml
      - ./tsukimi-core:/tsukimi-core
      - target-cache:/app/target
      - cargo-cache:/usr/local/cargo/registry
    ports:
      - "3000:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - postgres

volumes:
  pgdata:
  cargo-cache:
  target-cache:
  node_modules:
