services:
  db-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tsukimi
      POSTGRES_PASSWORD: tsukimi
      POSTGRES_DB: tsukimi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  web:
    build:
      context: ./tsukimi-web
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - db-postgres
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - target-cache:/app/target
      - cargo-cache:/usr/local/cargo/registry
    ports:
      - "3000:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - db-postgres

volumes:
  pgdata:
  cargo-cache:
  target-cache:
