services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./Cargo.toml:/app/Cargo.toml
      - target-cache:/app/target
      - cargo-cache:/usr/local/cargo/registry
    ports:
      - "3000:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true
volumes:
  cargo-cache:
  target-cache:
