[package]
name = "tsukimi-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
sqlx = { version = "0.8.6", features = ["uuid", "time"] }
time = "0.3.41"
uuid = { version = "1.17.0", features = ["serde"] }
