[package]
name = "tsukimi-extension"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
# crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.44.0"

[package.metadata.component]
target = { path = "wit" }
